from __future__ import annotations

SUPERVISOR_HTML = r'''<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#050914">
  <title>Louis OS — Superviseur</title>
  <style>
    :root{--bg:#050914;--panel:#0b1324;--panel2:#101a30;--line:#1d2b47;--text:#f4f7ff;--muted:#8fa4c8;--cyan:#19c4f4;--blue:#4c7dff;--green:#21d89d;--amber:#ffc857;--red:#ff6685}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,rgba(76,125,255,.16),transparent 30%),linear-gradient(160deg,#030711,#07101e 55%,#040812);color:var(--text);font:14px/1.45 Inter,system-ui,-apple-system,Segoe UI,sans-serif;min-height:100vh}.wrap{max-width:1500px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.top h1{margin:0;font-size:27px}.sub{color:var(--muted);margin-top:4px}.pill{display:inline-flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:999px;padding:8px 11px;background:#081120;color:var(--muted)}.dot{width:9px;height:9px;border-radius:50%;background:var(--amber)}.dot.ok{background:var(--green);box-shadow:0 0 12px rgba(33,216,157,.75)}.dot.bad{background:var(--red)}.grid{display:grid;gap:14px}.metrics{grid-template-columns:repeat(6,minmax(0,1fr));margin-bottom:14px}.card{border:1px solid var(--line);background:linear-gradient(155deg,rgba(16,26,48,.96),rgba(7,13,27,.96));border-radius:16px;padding:17px}.label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.value{font-size:27px;font-weight:800;margin-top:5px}.note{font-size:11px;color:var(--muted);margin-top:3px}.two{grid-template-columns:1.1fr .9fr;margin-bottom:14px}.three{grid-template-columns:repeat(3,1fr)}h2{font-size:16px;margin:0 0 13px}.row{display:grid;grid-template-columns:165px 1fr;gap:12px;padding:9px 0;border-bottom:1px solid rgba(100,130,180,.14)}.row:last-child{border-bottom:0}.key{color:var(--muted)}.val{overflow-wrap:anywhere}.bar{height:10px;background:#07101d;border:1px solid var(--line);border-radius:99px;overflow:hidden;margin-top:9px}.fill{height:100%;background:linear-gradient(90deg,var(--cyan),var(--blue));width:0}.status{font-weight:700}.oktxt{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.mission{padding:12px;border:1px solid var(--line);border-radius:12px;background:#081120;margin-top:9px}.big{font-size:16px;font-weight:750}.footer{color:var(--muted);font-size:11px;margin-top:14px;text-align:right}.actions{display:flex;gap:8px}.btn{border:1px solid var(--line);background:#0b1629;color:var(--text);border-radius:10px;padding:9px 12px;text-decoration:none;cursor:pointer}.btn:hover{border-color:var(--blue)}@media(max-width:1100px){.metrics{grid-template-columns:repeat(3,1fr)}.three{grid-template-columns:1fr 1fr}}@media(max-width:720px){.wrap{padding:14px}.top{display:block}.actions{margin-top:12px}.metrics{grid-template-columns:1fr 1fr}.two,.three{grid-template-columns:1fr}.row{grid-template-columns:120px 1fr}.value{font-size:23px}}
  </style>
</head>
<body>
<div class="wrap">
  <div class="top">
    <div><h1>Louis OS — Dashboard Superviseur</h1><div class="sub">État instantané de la VM, autonomie, consommation de cycle, navigateur et performance économique.</div></div>
    <div class="actions"><a class="btn" href="/">← Louis OS</a><button class="btn" id="refresh">Actualiser</button><div class="pill"><span id="dot" class="dot"></span><span id="fresh">Connexion…</span></div></div>
  </div>

  <div class="grid metrics">
    <div class="card"><div class="label">VM / Worker</div><div id="workerState" class="value">—</div><div id="workerNote" class="note">—</div></div>
    <div class="card"><div class="label">Utilisation productive</div><div id="util" class="value">—</div><div class="bar"><div id="utilBar" class="fill"></div></div></div>
    <div class="card"><div class="label">Temps actif / cycle</div><div id="active" class="value">—</div><div id="cycleBudget" class="note">—</div></div>
    <div class="card"><div class="label">Actions / cycle</div><div id="actions" class="value">—</div><div id="cycle" class="note">—</div></div>
    <div class="card"><div class="label">Soumissions vérifiées</div><div id="submissions" class="value">—</div><div class="note">externes confirmées</div></div>
    <div class="card"><div class="label">Revenu vérifié</div><div id="revenue" class="value">—</div><div class="note">encaissé / confirmé</div></div>
  </div>

  <div class="grid two">
    <div class="card"><h2>Mission & autonomie</h2><div class="row"><div class="key">Phase VM</div><div id="phase" class="val">—</div></div><div class="row"><div class="key">Action en cours</div><div id="activity" class="val">—</div></div><div class="row"><div class="key">Prochaine action</div><div id="next" class="val">—</div></div><div class="row"><div class="key">Blocage principal</div><div id="blocker" class="val">—</div></div><div class="row"><div class="key">Autorité</div><div id="authority" class="val">—</div></div><div class="row"><div class="key">Score autonomie</div><div id="score" class="val">—</div></div></div>
    <div class="card"><h2>Pipeline économique</h2><div class="row"><div class="key">Exécutable maintenant</div><div id="executeNow" class="val">—</div></div><div class="row"><div class="key">Préparer puis gate</div><div id="prepare" class="val">—</div></div><div class="row"><div class="key">Étape mission</div><div id="missionStage" class="val">—</div></div><div class="mission"><div class="label">Mission active</div><div id="mission" class="big">Aucune mission projetée</div></div></div>
  </div>

  <div class="grid three">
    <div class="card"><h2>Navigateur VM</h2><div class="row"><div class="key">État</div><div id="browserStatus" class="val">—</div></div><div class="row"><div class="key">Page</div><div id="browserTitle" class="val">—</div></div><div class="row"><div class="key">URL</div><div id="browserUrl" class="val">—</div></div><div class="row"><div class="key">HTTP</div><div id="browserHttp" class="val">—</div></div><div class="row"><div class="key">Prochaine étape</div><div id="browserNext" class="val">—</div></div></div>
    <div class="card"><h2>Consommation du cycle</h2><div class="row"><div class="key">Budget</div><div id="budget" class="val">—</div></div><div class="row"><div class="key">Écoulé</div><div id="elapsed" class="val">—</div></div><div class="row"><div class="key">Restant</div><div id="remaining" class="val">—</div></div><div class="row"><div class="key">Budget consommé</div><div id="consumed" class="val">—</div></div><div class="bar"><div id="consumedBar" class="fill"></div></div></div>
    <div class="card"><h2>Qualité d'exécution</h2><div class="row"><div class="key">Heartbeat</div><div id="heartbeat" class="val">—</div></div><div class="row"><div class="key">Commande bus</div><div id="bus" class="val">—</div></div><div class="row"><div class="key">Erreur bus</div><div id="busError" class="val">—</div></div><div class="row"><div class="key">Capacité inutilisée</div><div id="unused" class="val">—</div></div></div>
  </div>
  <div id="updated" class="footer">—</div>
</div>
<script>
const $=id=>document.getElementById(id); const fmt=(v,f='—')=>v===null||v===undefined||v===''?f:v; const pct=v=>Number.isFinite(Number(v))?Math.max(0,Math.min(100,Number(v))):0;
function statusClass(el,v){el.classList.remove('oktxt','warn','bad');const s=String(v||'').toLowerCase();el.classList.add(['running','healthy','completed','ok'].includes(s)?'oktxt':(['failed','error','blocked'].includes(s)?'bad':'warn'));}
async function load(){try{const r=await fetch('/live',{cache:'no-store'}); if(!r.ok) throw new Error('HTTP '+r.status); const d=await r.json(); const state=fmt(d.status,d.available?'running':'unknown'); $('workerState').textContent=state; statusClass($('workerState'),state); $('workerNote').textContent=fmt(d.worker,'gcp_vm_monetization_worker'); $('phase').textContent=fmt(d.phase); $('activity').textContent=fmt(d.current_activity||d.live_worker_current_command||d.autonomy_action); $('next').textContent=fmt(d.next_action); $('blocker').textContent=fmt(d.primary_blocker,'aucun'); $('authority').textContent=fmt(d.autonomy_authority); $('score').textContent=fmt(d.autonomy_score); $('executeNow').textContent=fmt(d.execute_now,0); $('prepare').textContent=fmt(d.prepare_then_gate,0); $('missionStage').textContent=fmt(d.mission_stage); const m=d.current_mission; $('mission').textContent=m?(m.title||m.name||JSON.stringify(m)):'Aucune mission projetée'; $('submissions').textContent=fmt(d.external_submissions_verified,0); $('revenue').textContent=(Number(d.revenue_verified_eur||0)).toFixed(2)+' €'; const u=pct(d.productive_utilization_pct); $('util').textContent=u.toFixed(1)+' %'; $('utilBar').style.width=u+'%'; $('active').textContent=Number(d.active_work_seconds||0).toFixed(1)+' s'; $('cycleBudget').textContent='budget '+fmt(d.cycle_budget_seconds,0)+' s'; $('actions').textContent=fmt(d.actions_completed_in_cycle,0); $('cycle').textContent='cycle #'+fmt(d.cycle,'—'); $('budget').textContent=fmt(d.cycle_budget_seconds,0)+' s'; $('elapsed').textContent=fmt(d.cycle_elapsed_seconds,0)+' s'; $('remaining').textContent=fmt(d.cycle_remaining_seconds,0)+' s'; const c=pct(d.budget_consumed_pct); $('consumed').textContent=c.toFixed(1)+' %'; $('consumedBar').style.width=c+'%'; $('browserStatus').textContent=fmt(d.browser_status); statusClass($('browserStatus'),d.browser_status); $('browserTitle').textContent=fmt(d.browser_title); $('browserUrl').textContent=fmt(d.browser_final_url); $('browserHttp').textContent=fmt(d.browser_http_status); $('browserNext').textContent=fmt(d.browser_next_action); $('heartbeat').textContent=fmt(d.heartbeat_interval_seconds,'—')+' s'; $('bus').textContent=d.vm_command_bus_last_processed?JSON.stringify(d.vm_command_bus_last_processed):'aucune commande récente'; $('busError').textContent=fmt(d.vm_command_bus_error,'aucune'); $('unused').textContent=fmt(d.unused_capacity_reason,'aucune'); $('updated').textContent='Dernière télémétrie : '+fmt(d.updated_at||d.checked_at); const ok=['running','healthy','completed'].includes(String(state).toLowerCase()); $('dot').className='dot '+(ok?'ok':'bad'); $('fresh').textContent=ok?'VM en ligne':'État à vérifier';}catch(e){$('dot').className='dot bad';$('fresh').textContent='Télémétrie indisponible';$('updated').textContent=String(e)}}
$('refresh').addEventListener('click',load); load(); setInterval(load,5000);
</script>
</body></html>'''
